name: Version Update

on:
  push:
    branches:
      - versionauto

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (needed for script execution)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Filter changes
        id: filter_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            specific_folder:
              - 'NetworkManager/**'  # Replace with the path to your specific folder

      - name: Debug filtered changes
        run: |
            echo "Modified files:"
            echo "${{ steps.filter_changes.outputs.modified_files }}"

      - name: Output repository name for debugging
        run: echo "The repository is ${{ github.repository }}"

      - name: Increment version if first commit
        if: steps.filter_changes.outputs.folder == 'true' && github.repository == 'gururaajar/rdkservices'  # Replace with the owner and repository name
        run: python NetworkManager/NetworkManager-version-update.py

      - name: Commit version update
        if: steps.filter_changes.outputs.folder == 'true' && github.repository == 'gururaajar/rdkservices'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NetworkManager/CMakeLists.txt docs/api/NetworkManagerPlugin.md
          git commit -m "CI: Increment the version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
