name: Version Update

on:
  push:
    branches:
      - test_version

jobs:
  update_version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (needed for script execution)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Increment version
        run: python NetworkManager/NetworkManager-version-update.py

      - name: Commit version update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NetworkManager/CMakeLists.txt docs/api/NetworkManagerPlugin.md
          git commit -m "CI: Incremented the version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
