name: Version Update

on:
  push:
    branches:
      - versionauto

jobs:
  update_version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (needed for script execution)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine if new commit
        id: commit_check
        run: |
          # Determine the base branch
          BASE_BRANCH=${{ github.event.pull_request.base.ref || 'sprint/24Q2' }}
          echo "BASE_BRANCH=${BASE_BRANCH}"
          # Find the point where the current branch diverged from the base branch
          MERGE_BASE=$(git merge-base HEAD origin/${BASE_BRANCH})
          echo "MERGE_BASE=${MERGE_BASE}"
          # Count the number of commits from that point
          COMMIT_COUNT=$(git rev-list --count HEAD ^${MERGE_BASE})
          echo "COMMIT_COUNT=${COMMIT_COUNT}" >> $GITHUB_ENV
          # Check if the current commit is already in the base branch
          COMMIT_EXISTS=$(git branch --contains HEAD | grep -q ${BASE_BRANCH} && echo "true" || echo "false")
          echo "COMMIT_EXISTS=${COMMIT_EXISTS}" >> $GITHUB_ENV

      - name: Increment version if first commit
        if: env.COMMIT_EXISTS == 'false'
        run: python NetworkManager/NetworkManager-version-update.py

      - name: Commit version update
        if: env.COMMIT_EXISTS == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NetworkManager/CMakeLists.txt docs/api/NetworkManagerPlugin.md
          git commit -m "CI: Increment the version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
