name: Version Update

on:
  push:
    branches:
      - versionauto

jobs:
  update_version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python (needed for script execution)
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Fetch all branches
        run: git fetch --all

      - name: Determine if new commit
        id: commit_check
        run: |
          # File to store the last processed commit hash
          STATE_FILE=".github/last_commit_hash.txt"
          
          # Get the latest commit hash
          LATEST_COMMIT_HASH=$(git rev-parse HEAD)
          echo "LATEST_COMMIT_HASH=${LATEST_COMMIT_HASH}"

          # Check if the state file exists
          if [ -f $STATE_FILE ]; then
            LAST_COMMIT_HASH=$(cat $STATE_FILE)
            echo "LAST_COMMIT_HASH=${LAST_COMMIT_HASH}"
          else
            LAST_COMMIT_HASH=""
          fi

          # Check if the commit hash has changed
          if [ "$LATEST_COMMIT_HASH" != "$LAST_COMMIT_HASH" ]; then
            echo "IS_NEW_COMMIT=true" >> $GITHUB_ENV
          else
            echo "IS_NEW_COMMIT=false" >> $GITHUB_ENV
          fi

      - name: Increment version if first commit
        if: env.IS_NEW_COMMIT == 'true'
        run: python NetworkManager/NetworkManager-version-update.py

      - name: Commit version update
        if: env.IS_NEW_COMMIT == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NetworkManager/CMakeLists.txt docs/api/NetworkManagerPlugin.md
          git commit -m "CI: Incrementing the version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update last processed commit hash
        if: env.IS_NEW_COMMIT == 'true'
        run: |
          echo $LATEST_COMMIT_HASH > .github/last_commit_hash.txt
          git add .github/last_commit_hash.txt
          git commit -m "ci: update last processed commit hash"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
